### ISSUE TITLE
Glaxx block face always visible?

### ISSUE THREAD

**Issue by 34486** [TobsenD/XTones-Reworked#4] opened 2023-08-27 14:38 UTC
When placing Glaxx, you can look through the "glass" block and see the face of the other "glass" blocks. I don't know if this is a connected texture issue or not? I don't have any form of CTM installed on 1.19.2. 

Maybe its a setting I have changed wrong?

**Comment by TobsenD** [comment] 2023-08-29 15:59
Hi, yes I can confirm that this is a bug. It was fixed with version 1.0.2.

I created the releases and load them after Curse and Modrinth.

**Closed as completed by TobsenD** 2023-08-29 15:59 UTC
Labels: bug

**Comment by 34486** [comment] 2023-08-29 22:41
I should have asked while I was at it: https://github.com/XFactHD/FramedBlocks/issues/299

Are you able to make blocks a block entity so it will work with the FraemdBlocks mod? I don't think I should reopen or open a new issue for this as its not really an issue, just something maybe you could update/add?

**Comment by TobsenD** [comment] 2023-08-30 06:20
I'll take a look at it as soon as I find the time.

**Comment by lays24mc** [comment] 2023-08-30 11:41
@34486 can you test it again in the new version of Xtones Reworked for 1.19.2? Because I can place all blocks in Framed Blocks "frames" :)

Edit: After a test. Only GLAXX wont work in the frames

![grafik](https://github.com/TobsenD/XTones-Reworked/assets/38819519/51f0a8af-2d48-4a2a-a7bf-3502c268be54)

**Comment by TobsenD** [comment] 2023-08-30 20:11
Done @34486 and @lays24mc , see #5

**Comment by 34486** [comment] 2023-09-02 23:42
Yes, thank you! It does work, but also GLAXX is working in framed blocks for me too!!! Including the patch for always seeing the face, all works great! Thank you both very much for the support!
